package com.accusharp.hrms.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * A raw punch written straight into {@code device_logs} by the eSSL biometric
 * device. This application only ever reads it - there is no ingestion endpoint.
 */
@Entity
@Table(
        name = "device_logs",
        indexes = {
                @Index(
                        name = "idx_device_logs_user_date",
                        columnList = "user_id,log_date"
                ),
                @Index(
                        name = "idx_device_logs_source_id",
                        columnList = "device_log_id"
                )
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DeviceLog {

    /**
     * Unique ID generated by our HRMS database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Original ID coming from the eSSL/source database.
     *
     * This ID is NOT globally unique because every source database
     * can start from 1 again.
     */
    @Column(name = "device_log_id", nullable = false)
    private Long deviceLogId;

    @Column(name = "device_id")
    private Long deviceId;

    @Column(name = "log_date", nullable = false)
    private LocalDateTime logDate;

    @Column(name = "user_id", nullable = false, length = 50)
    private String userId;
}